# Generated by Django 5.0.4 on 2024-04-21 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_comment_commentreport_projectreport'),
        ('projects', '0003_tag_comment_commentreport_projectreport_projecttag'),
    ]

    operations = [
    ]
