# Generated by Django 5.0.4 on 2024-04-14 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Egyptian phone number.', regex='^01[0125]{1}[0-9]{8}$')]),
        ),
    ]
